### ISSUE TITLE
SCAM ALERT !!!

### ISSUE THREAD

**Issue by jugi1** [bytepaydev/Bytepay#1]
!!!    SCAM ALERT   !!!
Connection with Edgy...iodev...CropCoin

BYTEPAY SCAM

Asking 0.5 BTC for Masternode
BAN People on Discord for asking questions
Altering Discord and Bitcointalk forum
4 fake developers
5 fake years expiriance
Account at Bitcointalk opened one month ago
Topic on Bitcointalk is selfmoderated and altered - he just erase all that he does not like
Premine 4%

Changing prices by minute. Escrow forbiden. He works only on trust.
http://fs1.directupload.net/images/180408/e7q9q3zh.jpg
http://fs1.directupload.net/images/180408/83y3jtk6.jpg

More info:
https://bitcointalk.org/index.php?topic=3283379.0

**Comment by bytepaydev** [comment]
you wont  get free coins.keep fudding
